#!/usr/bin/env python
"""Генератор батчей 867-871 с полными 50 KnowledgeUnits каждый."""
from __future__ import annotations

import os

OUT = "docs/knowledge/world_skills_core/ru"

BATCHES = [
    {
        "num": 867,
        "file": "1009_BATCH_867_LOCKSMITH_RESIDENTIAL.ru.md",
        "title": "Locksmith — Residential & Commercial",
        "ns": "locksmith.ops",
        "scope": "rekey, deadbolt, smart_lock, safe, bump_key, master_key, door_prep",
        "facts": [
            ("rekey_pin_tumbler_cylinder", "Rekey — Pin Tumbler Cylinder", "METHOD",
             "Перекодировка цилиндрового замка заменой штифтов под новый ключ без смены корпуса. Извлечь цилиндр по инструкции производителя, выбить старые нижние и верхние штифты, подобрать новый комплект по глубине насечек нового ключа, установить пружины и собрать. Проверить плавность поворота и отсутствие заедания.",
             "Неверная длина верхнего штифта — замок не открывается ни старым, ни новым ключом."),
            ("deadbolt_strike_plate_reinforce", "Deadbolt — Strike Plate Reinforcement", "METHOD",
             "Усиление ответной планки засова для защиты от выбивания двери. Установить металлическую накладку длиной 30-45 см с длинными винтами 7-10 см в стойку, а не только в облицовку. Центр отверстия засова совпадает с центром планки. При необходимости — box strike с металлической коробкой.",
             "Короткие винты в гипсокартон не удерживают засов при ударе ногой."),
            ("smart_lock_door_prep", "Smart Lock — Door Prep Check", "METHOD",
             "Проверка двери перед установкой умного замка: толщина полотна 35-55 мм, диаметр отверстия 54 мм для цилиндра, backset 60 или 70 мм. Питание: батареи AA или провод 12-24 В. Wi-Fi/Zigbee мост для удалённого доступа. Резервный механический ключ обязателен.",
             "Умный замок на слабой батарее блокирует вход — менять батареи до сигнала 20%."),
            ("bump_key_resistance_pins", "Bump Key — Security Pins", "METHOD",
             "Повышение стойкости к bumping установкой security pins (spool, mushroom, serrated). При bump-атаке штифты клинят в камере. Комбинировать с высокобезопасным цилиндром и защитной накладкой на цилиндр.",
             "Обычные латунные штифты открываются bump-ключом за секунды."),
            ("master_key_system_design", "Master Key — Hierarchy Design", "METHOD",
             "Проектирование мастер-ключевой системы: Great Grand Master → Grand Master → Master → Change key. Каждый уровень добавляет один общий штифт. Документировать bittings и уровни доступа. Ограничить копирование ключей на профильном станке с картой.",
             "Самодельный мастер-ключ без схемы штифтов делает всю систему небезопасной."),
            ("door_handing_determination", "Door Handing — LH/RH Determination", "METHOD",
             "Определение стороны открывания: встать снаружи (с улицы или коридора), смотреть на дверь. Петли слева — LH, справа — RH. Для замка с ручкой: направление защёлки (reversible или фиксированная). In-swing vs out-swing влияет на тип петель.",
             "Неверный handing — ручка и засов смотрят в противоположную сторону."),
            ("mortise_lock_installation", "Mortise Lock — Mortise Prep", "METHOD",
             "Установка врезного замка: фрезеровать карман в кромке двери по шаблону производителя. Глубина кармана = толщина корпуса. Отверстия под цилиндр и ручки сверлить из обеих сторон во избежание скола. Защёлка на высоте 100-110 см от пола.",
             "Слишком мелкий карман — корпус замка не входит и деформирует дверь."),
            ("key_duplication_blank_selection", "Key Duplication — Blank Selection", "METHOD",
             "Дублирование ключей: подобрать заготовку по профилю (KW1, SC1, Y1 и т.д.). Выровнять по оригиналу в зажиме. Проверить глубины насечек после копирования. Для высокобезопасных ключей — только авторизованный дилер с картой.",
             "Неверная заготовка — ключ входит, но не поворачивает цилиндр."),
            ("lock_lubrication_graphite_vs_oil", "Lock Lubrication — Graphite vs Oil", "METHOD",
             "Смазка замков: сухой графитовый порошок для цилиндровых механизмов. WD-40 только для очистки, затем удалить и нанести графит. Масло притягивает пыль и забивает камеру. PTFE-спрей допустим для защёлок.",
             "Масло в цилиндре через месяц превращается в липкую грязь."),
            ("safe_dial_combination_change", "Safe Dial — Combination Change", "METHOD",
             "Смена кода сейфового дискового замка: открыть по старому коду, снять крышку, установить change key, повернуть диски на новые числа по инструкции, проверить 3-5 раз, закрыть крышку. Записать код в защищённое место, не на сейфе.",
             "Смена кода без change key требует полной разборки механизма."),
            ("panic_bar_exit_device", "Panic Bar — Exit Device Install", "METHOD",
             "Установка антипанического устройства на пожарных выходах: горизонтальная планка открывает защёлку при нажатии. Fire-rated дверь требует сертифицированного устройства. Dogging для режима свободного хода. Проверить срабатывание с усилием не более 67 Н.",
             "Блокировка panic bar цепью — нарушение пожарных норм."),
            ("lock_pick_legal_ethics", "Lock Picking — Legal Context", "METHOD",
             "Правовой контекст вскрытия: работать только с документом на право собственности или доверенностью. Идентификация клиента обязательна. Вести журнал вызовов с адресом и типом работ. Инструменты только для лицензированных слесарей где требуется лицензия.",
             "Вскрытие без подтверждения права собственности — уголовная ответственность."),
            ("cylinder_overlay_attack", "Cylinder — Anti-Overlay Protection", "METHOD",
             "Защита цилиндра от выкручивания и overlay-атаки: security escutcheon с заклёпками, anti-drill пластины, hardened steel pin. Цилиндр не должен выступать более 3 мм наружу. Euro profile — security ring.",
             "Выступающий цилиндр обрезают и выкручивают пассатижами."),
            ("padlock_shackle_security", "Padlock — Shackle Hardness", "METHOD",
             "Выбор навесного замка: закалённая дужка 50+ HRC, защита от болтореза. Hidden shackle (protected) для ворот. Weatherproof корпус для улицы. Размер дужки под скобу без зазора для рычага.",
             "Мягкая дужка режется болторезом за 5 секунд."),
            ("keyless_entry_code_lock", "Keypad Lock — Code Management", "METHOD",
             "Кодовый замок: назначить master code и user codes. Менять код после смены жильцов. Anti-peep: вводить случайные цифры до и после кода. Блокировка после 5 неверных попыток. Резервный ключ или механический override.",
             "Один код на всех жильцов — невозможно отозвать доступ одного человека."),
            ("sliding_door_lock", "Sliding Door — Foot Bolt & Hook", "METHOD",
             "Защита раздвижной двери: upper track pin, charley bar, double bolt hook lock. Стеклянная дверь — специальная защёлка без сколов. Проверить выравнивание створки для плавного защёлкивания.",
             "Только палка в дорожке — не защищает от подъёма створки из паза."),
            ("lock_impressioning_technique", "Impressioning — Key From Lock", "METHOD",
             "Изготовление ключа по следам в цилиндре: вставить пустую заготовку, поворачивать с лёгким давлением, отмечать точки на лезвии, подпиливать, повторять до открытия. Только для легальных вызовов с подтверждением права.",
             "Техника требует 20-40 итераций — не для экстренного вызова."),
            ("electric_strike_wiring", "Electric Strike — Wiring & Fail Mode", "METHOD",
             "Электрозащёлка: fail-safe (открыта без питания) для эвакуации, fail-secure (закрыта) для периметра. Питание 12/24 В DC, диод для защиты от обратной ЭДС. REX (request to exit) кнопка обязательна с внутренней стороны.",
             "Fail-safe на наружной двери — открывается при отключении электричества."),
            ("lock_cylinder_sizes_euro", "Euro Cylinder — Size Measurement", "METHOD",
             "Подбор евроцилиндра: измерить от центра винта до края двери с обеих сторон. Стандарт 30/30, 35/35, 40/40 мм. Thumbturn с внутренней стороны для квартир. Security grade 2-3 для входных дверей.",
             "Длинный цилиндр снаружи — уязвимость для перелома."),
            ("broken_key_extraction", "Broken Key — Extraction Tools", "METHOD",
             "Извлечение обломанного ключа: спрей-смазка, extractor hooks по форме бородок, не повредить штифты. При глубоком обломе — снять цилиндр и вытолкнуть с обратной стороны. Запасной ключ для проверки после извлечения.",
             "Плоскогубцы в камере гнут штифты и ломают цилиндр."),
            ("door_closer_adjustment", "Door Closer — Sweep & Latch Speed", "METHOD",
             "Регулировка доводчика: sweep speed (закрывание), latch speed (последние 15 см), backcheck (сопротивление при открытии). ADA: не более 5 секунд до 90°, усилие открытия ≤ 22 Н. Проверить полное защёлкивание.",
             "Слишком быстрый latch — дверь хлопает и не запирается."),
            ("multipoint_lock_alignment", "Multipoint Lock — Point Alignment", "METHOD",
             "Многоточечный замок на входной двери: верхний, средний, нижний засовы должны входить в ответные планки одновременно. Регулировка петель и центрального замка. Проверить при перепадах температуры (расширение ПВХ).",
             "Один незашедший крюк блокирует поворот ключа."),
            ("locksmith_vehicle_storage", "Locksmith Van — Tool Organization", "METHOD",
             "Мобильная мастерская: дублировщик ключей, pick set, plug spinner, scope, drill kit с hardened bits, replacement cylinders top 10 profiles. Blank inventory по региону. Laptop для smart lock programming.",
             "Отсутствие blank KW1 на вызове — повторный визит и потеря времени."),
            ("safe_opening_drill_resort", "Safe Opening — Drill as Last Resort", "METHOD",
             "Вскрытие сейфа сверлением только с разрешением владельца и когда манипуляция невозможна. Знать расположение relocker и glass plate. Починить или заменить замок после вскрытия. Документировать повреждения.",
             "Сверление без знания relocker — необратная блокировка сейфа."),
            ("lock_bumping_prevention", "Bump Prevention — Overall Strategy", "METHOD",
             "Комплексная защита: high-security cylinder + security pins + reinforced strike + door viewer + alarm. Не полагаться только на brand name. Grade 1 ANSI/BHMA для входных дверей.",
             "Дешёвый «security» замок часто имеет те же штифты, что и обычный."),
            ("ic_core_rekeying", "IC Core — Interchangeable Core Rekey", "METHOD",
             "Сменный сердечник (IC): открыть control key, извлечь core, вставить новый с другим operating key. Control key хранить отдельно. Best, Falcon, Schlage SC — разные системы несовместимы.",
             "Потеря control key — смена всего корпуса замка."),
            ("lock_installation_height", "Lock Height — Standard Placement", "METHOD",
             "Стандартная высота замка: 100-110 см от пола до центра цилиндра. Deadbolt на 15 см выше ручки. Детские учреждения — ниже по нормативам. Согласовать с клиентом при нестандартных дверях.",
             "Слишком высокий замок — неудобство и ошибки при открытии."),
            ("restricted_keyway_policy", "Restricted Keyway — Copy Protection", "METHOD",
             "Ограниченный профиль ключа: дубликаты только у дилера с картоой владельца. Medeco, Mul-T-Lock, Assa Abloy. Патент на профиль ограничивает копирование. Документировать владельца карты.",
             "Потеря карты — процедура перевыпуска через производителя."),
            ("garage_door_lock", "Garage Door — Manual Lock & Release", "METHOD",
             "Блокировка гаражной двери: slide lock на направляющую, или отключить opener и установить padlock на трос (осторожно — не при натянутом тросе). Emergency release только с защитой от wire hook снаружи.",
             "Открытый emergency release — классическая точка взлома гаража."),
            ("window_lock_pins", "Window — Pin Lock & Ventilation", "METHOD",
             "Блокировка окон: pin lock через раму, charley bar на откидных. Ventilation position с ограничителем 10 см. Детская безопасность — не более 10 см зазор. Двойной замок на первом этаже.",
             "Открытое на проветривание окно без ограничителя — лаз для злоумышленника."),
            ("lock_corrosion_coastal", "Coastal — Corrosion Resistant Hardware", "METHOD",
             "Приморская зона: нержавеющая сталь 316, латунь с покрытием, пластиковые компоненты в механизме. Смазка marine-grade. Регулярная промывка пресной водой от соли.",
             "Обычная латунь в солёном воздухе закисает за 1-2 года."),
            ("tenant_lockout_protocol", "Tenant Lockout — Verification Protocol", "METHOD",
             "Вскрытие для арендатора: проверить ID, договор аренды, звонок арендодателю при сомнениях. Фото ID в журнале. Non-destructive methods first. Счёт арендодателю или арендатору по договору.",
             "Вскрытие без верификации — риск помощи мошеннику."),
            ("lock_grade_ansi_bhma", "Lock Grade — ANSI/BHMA Ratings", "METHOD",
             "Классификация замков: Grade 1 — коммерция, 1 млн циклов. Grade 2 — жилые входные. Grade 3 — внутренние двери. Проверять маркировку на упаковке и корпусе. Цена коррелирует с grade.",
             "Grade 3 на входной двери — быстрый износ и слабая защита."),
            ("magnetic_lock_hold_force", "Maglock — Holding Force Calculation", "METHOD",
             "Электромагнитный замок: сила удержания 300-1200 lbs по задаче. Питание с UPS для fail-safe. Bond sensor подтверждает прижатие. Не использовать на fire exit без RTE и fire release.",
             "Слабый maglock на стеклянной двери — отрыв при толчке."),
            ("lock_drill_resistant", "Drill Resistant — Hardened Inserts", "METHOD",
             "Сверлоустойчивый цилиндр: hardened steel pins, anti-drill plate, rotating pins при сверлении. Ball bearings в камере. Security escutcheon с закалённой вставкой.",
             "Обычный цилиндр сверлится за 30 секунд мощной дрелью."),
            ("key_control_register", "Key Control — Register & Issuance", "METHOD",
             "Учёт ключей в организации: номер ключа, владелец, дата выдачи, подпись. Периодический аудит. Возврат при увольнении. Master key inventory ограничен.",
             "Без реестра невозможно знать, сколько копий в обороте."),
            ("lock_warranty_void", "Warranty — Installation Void Conditions", "METHOD",
             "Гарантия производителя: не распространяется при сверлении корпуса, модификации, неправильной установке. Сохранять чек и оригинальную упаковку. Регистрация продукта онлайн для extended warranty.",
             "Самостоятельная установка с ошибкой — отказ в гарантийной замене."),
            ("door_reinforcement_kit", "Door Jamb — Reinforcement Kit", "METHOD",
             "Усиление коробки двери: steel wrap на стойку, 90 см длинные винты в стойку через петли. Door devil или similar на кромку. Распределение удара по всей высоте.",
             "Слабая стойка ломается вместе с петлями при kick-атаке."),
            ("locksmith_pricing_transparency", "Pricing — Transparent Quote", "METHOD",
             "Оценка стоимости: call-out fee + labor + parts + после-hours surcharge. Озвучить до начала работ. Согласовать замену vs repair. Письменная смета для коммерции.",
             "Низкая цена по телефону + наценка на месте — потеря доверия клиента."),
            ("biometric_fingerprint_enroll", "Biometric — Fingerprint Enrollment", "METHOD",
             "Регистрация отпечатков: 2-3 пальца на пользователя, несколько углов. Admin reset через master code. Резервный PIN и ключ. Очистка сенсора спиртом ежемесячно.",
             "Мокрые или повреждённые пальцы — ложные отказы входа."),
            ("lock_freezing_deicer", "Frozen Lock — De-icer Protocol", "METHOD",
             "Замёрзший замок: de-icer spray (не горячая вода — повторное замерзание). Прогреть ключ перед вставкой. Защитный колпачок на цилиндр зимой. Графит после оттаивания.",
             "Горячая вода в замок — лёд через час снова."),
            ("gate_lock_self_closing", "Gate Lock — Self-Closing Hinge", "METHOD",
             "Замок на калитке: self-closing hinges, latch на уровне 100 см, padlock или lever lock. Зазор под расширение дерева. Weatherproof исполнение.",
             "Просевшая калитка — засов не попадает в планку."),
            ("locksmith_insurance_liability", "Liability — Insurance Coverage", "METHOD",
             "Страхование слесаря: general liability, errors & omissions. Покрытие ущерба при ошибочном вскрытии. Bond для коммерческих контрактов.",
             "Работа без страховки — личная ответственность за тысячи долларов ущерба."),
            ("safe_deposit_drill_point", "Safe Deposit — Drill Point Knowledge", "METHOD",
             "Точки сверления сейфов: изучить модель перед работой. Relocker glass — останов при разбитии. Hard plate — смена свёрл. Manipulation preferred over drill.",
             "Случайное сверление в relocker — сейф заблокирован навсегда."),
            ("lock_cylinder_cam_orientation", "Cylinder Cam — Orientation Check", "METHOD",
             "Ориентация кулачка цилиндра: при повороте ключом кулачок должен нажимать на механизм засова. 12 или 6 часов в зависимости от замка. Проверить до фиксации винтом.",
             "Перевёрнутый кулачок — ключ поворачивается, засов не двигается."),
            ("peephole_viewer_install", "Door Viewer — Height & Angle", "METHOD",
             "Установка глазка: высота 145-160 см, угол 160-200° для широкого обзора. Сверление 12-14 мм из обеих сторон. Privacy cover с внутренней стороны.",
             "Низкий глазок — дети видят, взрослые нет."),
            ("locksmith_emergency_priority", "Emergency — Triage Priority", "METHOD",
             "Приоритет вызовов: ребёнок заперт > медицинский > коммерческая блокировка > жилое. ETA озвучить. При угрозе жизни — направить в экстренные службы параллельно.",
             "Задержка при ребёнке в машине — критическая ошибка."),
            ("lock_set_finish_matching", "Finish — Matching Existing Hardware", "METHOD",
             "Подбор отделки: satin nickel, oil rubbed bronze, polished brass, matte black. PVD покрытие долговечнее на улице. Смешивать finish на одной двери не рекомендуется.",
             "Разная отделка на ручке и deadbolt — эстетика и коррозия по-разному."),
            ("locksmith_tool_maintenance", "Tools — Calibration & Maintenance", "METHOD",
             "Обслуживание инструмента: калибровка дублировщика ключей, заточка свёрл, чистка pick set. Замена worn clamps. Проверка battery-powered tools перед выездом.",
             "Тупой дублировщик — брак ключей и возвраты клиентов."),
            ("lock_bypass_legal_notice", "Bypass Techniques — Documentation", "METHOD",
             "При использовании bypass (shim, bypass tool) — документировать в акте. Только на собственных или авторизованных объектах. Обучение в сертифицированных школах (ALOA и аналоги).",
             "Публикация bypass без контекста легальности — репутационный риск."),
        ],
    },
    {
        "num": 868,
        "file": "1010_BATCH_868_PRESSURE_WASHING_OPS.ru.md",
        "title": "Pressure Washing — Commercial & Residential",
        "ns": "pressurewash.ops",
        "scope": "psi, nozzle, detergent, surface, safety, fleet, concrete, wood, roof",
        "facts": [
            ("psi_surface_selection", "PSI — Surface Selection Guide", "METHOD",
             "Выбор давления по поверхности: авто 1200-1900 PSI, дерево 500-1200, бетон 2500-3500, кирпич 1500-2500. GPM важен для смыва грязи. Меньше PSI на мягких поверхностях предотвращает повреждение.",
             "3500 PSI на мягкой древесине — волокна поднимаются и поверхность шероховатая."),
            ("nozzle_degree_fan_pattern", "Nozzle — Degree & Fan Pattern", "METHOD",
             "Сопла: 0° pencil (опасно), 15° тяжёлая очистка, 25° универсал, 40° деликатная, soap nozzle 65°. Расстояние 30-60 см. Держать под углом, не перпендикулярно в одну точку.",
             "0° сопло на коже или краске — порез или снятие покрытия."),
            ("pretreatment_detergent_dwell", "Pretreatment — Detergent Dwell Time", "METHOD",
             "Предобработка: нанести моющее средство снизу вверх, выдержка 5-10 минут без высыхания. Low pressure soap application. Смыть сверху вниз. pH под материал: щелочное для жира, кислотное для минеральных отложений.",
             "Высохшее моющее оставляет разводы и пятна."),
            ("concrete_degreasing_oil", "Concrete — Oil & Grease Removal", "METHOD",
             "Масляные пятна на бетоне: абсорбент (cat litter), затем degreaser, щётка, промывка 2500+ PSI. Повтор при необходимости. Seal после очистки для защиты.",
             "Только вода не удаляет пропитанное масло из пор бетона."),
            ("wood_deck_soft_wash", "Wood Deck — Soft Wash Method", "METHOD",
             "Мягкая мойка дерева: 500-800 PSI, широкое сопло, вдоль волокон. Oxalic acid для потемнения. Не использовать 0°. Выдержать высыхание 48 ч перед seal/stain.",
             "Высокое давление на досках — полосы и поднятые волокна."),
            ("house_siding_vinyl", "Vinyl Siding — Wash Protocol", "METHOD",
             "Виниловый сайдинг: 1500 PSI max, снизу вверх мыть, сверху вниз смывать. Закрыть окна, защитить landscaping. Не направлять под overlap панелей. Mold: sodium hypochlorite soft wash.",
             "Вода под панели — плесень и гниение обшивки."),
            ("roof_soft_wash_no_pressure", "Roof — Soft Wash No Pressure", "METHOD",
             "Кровля: не использовать pressure washer на черепице — снятие гранул. Soft wash: химия (bleach + surfactant), низкое давление rinse. Walk только по dry areas или с harness.",
             "Pressure на asphalt shingles — аннулирование гарантии производителя."),
            ("fleet_wash_two_step", "Fleet Wash — Two-Step Method", "METHOD",
             "Мойка автопарка: acid-based pre-soak (алюминий осторожно), alkaline soap, rinse. 1200-1500 PSI. Закрыть кабины. Bottom-up для шасси. Recycle water где разрешено.",
             "Кислота на незащищённый алюминий — окисление и пятна."),
            ("surface_cleaner_attachment", "Surface Cleaner — Even Cleaning", "METHOD",
             "Роторная щётка для плоских поверхностей: равномерное давление, без полос. 18-28 дюймов для тротуаров. Overlap проходов 15%. Не останавливаться на месте.",
             "Остановка surface cleaner — круговое повреждение бетона."),
            ("water_supply_gpm_adequacy", "Water Supply — GPM Adequacy", "METHOD",
             "Подача воды: машина требует X GPM inlet — проверить кран и шланг 3/4\". Buffer tank при недостаточном потоке. Не гонять насос сухим.",
             "Недостаток подачи — cavitation насоса и поломка."),
            ("hot_water_grease_cutting", "Hot Water — Grease Cutting", "METHOD",
             "Горячая вода 80-90°C для жира и масла. Не на алюминии и некоторых красках. Burner diesel/propane. Разница с холодной водой критична на кухонных вытяжках.",
             "Кипяток на холодном стекле — трещина от термошока."),
            ("ladder_safety_pressure_wash", "Ladder Safety — While Washing", "METHOD",
             "Лестница: 3-point contact, не мыть себя отскоком. Extension ladder 1:4 угол. Harness на крыше. Не стоять на верхней ступени. Spotter при необходимости.",
             "Отдача шланга с лестницы — падение."),
            ("chemical_injection_ratio", "Chemical Injection — Ratio Setup", "METHOD",
             "Всасывание химии: downstream injector 10:1 до 50:1. Проверить draw rate. Отдельные контейнеры для кислоты и щелочи. Промыть систему после кислоты.",
             "Смешивание кислоты и отбеливателя — токсичный газ."),
            ("efflorescence_removal_masonry", "Efflorescence — Masonry Removal", "METHOD",
             "Высолы на кирпиче: сухая щётка сначала, затем mild acid (muriatic diluted 1:10), dwell 5 мин, rinse. Seal masonry после. Найти источник влаги.",
             "Сильная кислота — растворение раствора между кирпичами."),
            ("graffiti_removal_pressure", "Graffiti — Removal Technique", "METHOD",
             "Граффити: solvent или soda blast, затем low pressure rinse. Тест на скрытой зоне. Paint-compatible surface — не повредить substrate. Report для municipal contracts.",
             "Агрессивный solvent на пластике — помутнение."),
            ("gutter_exterior_wash", "Gutter Exterior — Wash Method", "METHOD",
             "Наружная мойка желобов: extension wand, 1500 PSI, угол вдоль. Не снимать gutter с креплений. Brightener для алюминия. Проверить flow после очистки.",
             "Давление внутрь gutter — срыв с кронштейнов."),
            ("pool_deck_slippery_algae", "Pool Deck — Algae & Slip Hazard", "METHOD",
             "Бассейн: sodium hypochlorite на скользкую плитку, scrub, rinse к drain не в бассейн. Предупредить о скользкости до высыхания. Non-slip coating опционально.",
             "Смыв химии в бассейн — нарушение химбаланса воды."),
            ("commercial_bid_pricing", "Commercial Bid — Pricing Model", "METHOD",
             "Коммерческая смета: $/sq ft по типу поверхности, сложность доступа, химия, travel, water reclaim. Walkthrough обязателен. Minimum charge за выезд.",
             "Цена без осмотра — недооценка времени в 2-3 раза."),
            ("water_reclaim_filtration", "Water Reclaim — Filtration System", "METHOD",
             "Рециркуляция воды: vacuum recovery, settlement, filtration, reuse. EPA и local discharge rules. Не сбрасывать oily water в storm drain.",
             "Штраф за сброс грязной воды в ливнёвку — тысячи долларов."),
            ("parking_garage_oil", "Parking Garage — Oil & Tire Marks", "METHOD",
             "Паркинг: degreaser, hot water, surface cleaner. Night work для минимизации трафика. Barricades и signs. Slip hazard signage до высыхания.",
             "Мойка днём — жалобы и аварии на мокром бетоне."),
            ("fence_wash_wood_metal", "Fence — Wood vs Metal Protocol", "METHOD",
             "Забор: дерево soft wash, металл 1500 PSI rust removal then prime/paint if needed. Vinyl 1200 PSI. Direction along boards. Protect plants with tarp.",
             "Поперёк досок — поднятие волокон и полосы."),
            ("driveway_seal_after_wash", "Driveway — Seal After Wash", "METHOD",
             "Подготовка к seal: полная сушка 24-48 ч, no rain forecast. Oil stains treated first. Uniform color before seal application by others or same contractor.",
             "Seal на влажный бетон — белёсость и отслоение."),
            ("equipment_maintenance_pump", "Pump — Maintenance Schedule", "METHOD",
             "Обслуживание: oil change pump, check valves, unloader, hoses inspection, O-rings. Winterize: antifreeze или drain. Fuel stabilizer для бензиновых.",
             "Замёрзшая вода в насосе — трещина корпуса."),
            ("hose_length_pressure_drop", "Hose — Length & Pressure Drop", "METHOD",
             "Длина шланга: каждые 50 футов — потеря давления. Диаметр 3/8\" для pro. Не перегибать. Quick connects rated for PSI.",
             "Дешёвый шланг — разрыв и травма при 3000 PSI."),
            ("client_property_protection", "Property Protection — Pre-Job", "METHOD",
             "Перед работой: фото состояния, закрыть outlets, tape meters, wet bags on doors, move furniture, cover plants. Walkthrough с клиентом после.",
             "Смытая краска с trim — спор без pre-job фото."),
            ("rust_stain_concrete_fertilizer", "Rust — Fertilizer Stain on Concrete", "METHOD",
             "Ржавые пятна от удобрений: oxalic or commercial rust remover, dwell, scrub, rinse. Iron particles from lawn — repeat treatment. Seal optional.",
             "Отбеливатель не удаляет iron rust — нужна кислота."),
            ("mold_mildew_house_wash", "Mold & Mildew — House Wash Mix", "METHOD",
             "Плесень на фасаде: SH 1-3% + surfactant, dwell, soft rinse. Protect plants (water before/after). PPE: goggles, gloves. No sun on drying chemical.",
             "Сухая химия на солнце — ожог растений и siding."),
            ("telescoping_wand_safety", "Telescoping Wand — Overhead Safety", "METHOD",
             "Телескопическая штанга: не выше recommended extension. Двуручный хват. Overhead power lines — минимум 10 футов. Fiberglass для электробезопасности.",
             "Алюминиевая штанга у ЛЭП — смертельный удар током."),
            ("insurance_workers_comp", "Insurance — GL & Workers Comp", "METHOD",
             "Страхование pressure washing: slip/fall, property damage, chemical exposure. COI для commercial clients. Equipment floater для theft.",
             "Повреждение окна клиента без GL — личный иск."),
            ("stripe_removal_thermoplastic", "Stripe Removal — Thermoplastic", "METHOD",
             "Снятие разметки: 3000+ PSI 0° или grinder, surface damage risk. Water blasting systems для airports. Permits для road work.",
             "Неправильное снятие — повреждение asphalt binder."),
            ("awning_canopy_clean", "Awning — Low Pressure Clean", "METHOD",
             "Маркизы: 500 PSI max, mild soap, brush gently. Acrylic fabric — no harsh solvent. Dry completely before retracting.",
             "Высокое давление — разрыв швов ткани."),
            ("dumpster_pad_sanitation", "Dumpster Pad — Sanitation Wash", "METHOD",
             "Площадка мусорного контейнера: degreaser, sanitizer, hot water, reclaim water. Frequency weekly/monthly по контракту. Odor neutralizer после.",
             "Сброс в drain без treatment — нарушение wastewater rules."),
            ("solar_panel_cleaning_caution", "Solar Panel — Cleaning Caution", "METHOD",
             "Солнечные панели: deionized water, no chemicals, soft brush or RO water system. Cool panels (утро). Не pressure — трещины cell. Check warranty terms.",
             "Tap water — mineral spots снижают выход kW."),
            ("brick_pavers_polymeric_sand", "Pavers — Polymeric Sand Caution", "METHOD",
             "Мойка брусчатки: не смыть polymeric sand из швов. 1500 PSI max angled. Re-sand joints если needed после. Seal pavers после полной сухости.",
             "Прямой jet в швы — вымывание затирки и смещение плит."),
            ("cold_weather_washing_limits", "Cold Weather — Operating Limits", "METHOD",
             "Мороз: не мыть при <4°C если freeze risk на surface. Antifreeze in pump only for storage. Ice on ground — slip. Hot water helps winter degrease.",
             "Вода замерзает на ступенях — ответственность за падение."),
            ("eco_friendly_detergent_choice", "Eco Detergent — Biodegradable Choice", "METHOD",
             "Биоразлагаемые моющие для LEED sites и чувствительных watersheds. SDS sheet on site. Phosphate-free. Client marketing value.",
             "Жёсткая химия у пруда — kill fish, штраф EPA."),
            ("multi_gun_crew_coordination", "Multi-Gun — Crew Coordination", "METHOD",
             "Бригада: один источник — распределение GPM между пистолетами. Не превышать pump capacity. Radio связь на больших объектах.",
             "Два gun на одном pump — падение PSI и недомыв."),
            ("stain_identification_test_patch", "Stain ID — Test Patch Protocol", "METHOD",
             "Неизвестное пятно: test patch 30×30 см, document result, adjust chemistry. Organic vs mineral vs oil — разные протоколы.",
             "Универсальная химия на всё — повреждение 30% поверхностей."),
            ("downstream_vs_upstream_inject", "Injector — Downstream vs Upstream", "METHOD",
             "Downstream: безопаснее для pump, слабее draw. Upstream: сильнее, риск для seals. Bleach только downstream на большинстве rigs.",
             "Chlorine upstream — corrosion pump internals."),
            ("client_education_maintenance", "Client Education — Maintenance Interval", "METHOD",
             "Рекомендации: house wash 12-24 мес, driveway 24 мес, roof soft wash по необходимости. Gutter clean separate. Maintenance contract discount.",
             "Раз в 5 лет — накопленный mold требует агрессивной химии."),
            ("pressure_gauge_calibration", "Gauge — Calibration Check", "METHOD",
             "Проверка PSI gauge на machine vs external gauge ежегодно. Unloader adjustment если drift. Log maintenance.",
             "Завышенный gauge — реальное повреждение при «безопасном» PSI."),
            ("wood_fence_gray_restoration", "Wood Fence — Gray Restoration", "METHOD",
             "Серый забор: sodium percarbonate brighten, oxalic acid neutralize, rinse. Stain within 48 h. 600-800 PSI along grain.",
             "Пропуск neutralize — stain не ляжет равномерно."),
            ("gum_removal_concrete", "Gum — Removal from Concrete", "METHOD",
             "Жвачка: freeze spray or heat gun, scrape, spot clean. Commercial gum remover. On hot asphalt — soften first.",
             "Scrape metal on decorative concrete — царапины."),
            ("signage_wash_delicate", "Signage — Delicate Surface Wash", "METHOD",
             "Вывески: 800 PSI, wide fan, no direct on LEDs or vinyl letters. Night wash для retail. Cherry picker license если needed.",
             "Давление на acrylic face — трещины и water inside sign."),
            ("before_after_photo_marketing", "Marketing — Before/After Photos", "METHOD",
             "Фото до/после с одинаковым ракурсом и освещением. Release form для использования на сайте. GPS tag для local SEO.",
             "Разный ракурс — клиент не видит разницу, нет доверия."),
            ("emergency_spill_response", "Spill — Chemical Spill Response", "METHOD",
             "Разлив химии: contain, absorbent, не смывать в storm. SDS procedures. Report если > threshold. Spill kit в truck.",
             "Смыв кислоты в gutter — damage downstream ecosystem."),
            ("noise_ordiance_hours", "Noise — Ordinance Hours", "METHOD",
             "Шум: residential zones 7:00-19:00 typical. Gas engine restrictions некоторые города. Electric units для quiet zones.",
             "Раннее утро gas washer — жалоба и потеря контракта."),
            ("trailer_mount_vs_skid", "Trailer vs Skid — Mobility Choice", "METHOD",
             "Trailer mount для multi-site. Skid для fixed commercial. Hose reels, tool boxes, water tank sizing по typical job.",
             "Маленький tank на большом driveway — 10 refill trips."),
            ("training_surface_damage", "Training — Recognize Damage Early", "METHOD",
             "Обучение: остановиться при etching, furring, paint peel. Adjust PSI/nozzle immediately. Document and notify client.",
             "«Домыть до конца» после etch — необратимый ущерб."),
        ],
    },
]

# Truncate for script size - add batches 869-871 in part 2
# For now write first 2 batches

def write_batch(b: dict) -> None:
    path = os.path.join(OUT, b["file"])
    lines = [
        f"# BATCH {b['num']}: {b['title']}",
        "",
        f"**KnowledgeUnits:** {len(b['facts'])}",
        f"**Namespace:** `{b['ns']}.*`",
        f"**Scope:** {b['scope']}",
        "",
        "| ID | KnowledgeUnit | Тип | Суть | Практический смысл |",
        "|---|---|---|---|---|",
    ]
    for suffix, title, typ, essence, practical in b["facts"]:
        fid = f"{b['ns']}.{suffix}"
        lines.append(f"| {fid} | {title} | {typ} | {essence} | {practical} |")
    lines.append("")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"Wrote {path} ({len(b['facts'])} facts)")


if __name__ == "__main__":
    for batch in BATCHES:
        write_batch(batch)
