const fs = require("fs");
const path = require("path");

const htmlPath = path.join(__dirname, "../static/console/index.html");
let h = fs.readFileSync(htmlPath, "utf8");

// Build I18N.en at runtime from file snippet
const enStart = h.indexOf("      en: {");
const enEnd = h.indexOf("      },\n    };", enStart);
const enSnippet = "const __EN = {" + h.slice(enStart + "      en: {".length, enEnd) + "};";
let I18N_EN;
eval(enSnippet.replace("const __EN", "I18N_EN ="));

const de = {};
for (const [key, val] of Object.entries(I18N_EN)) {
  de[key] = translate(key, val);
}

const patch =
  "\n    I18N.de = " +
  JSON.stringify(de, null, 2)
    .split("\n")
    .map((line, i) => (i === 0 ? line : "    " + line))
    .join("\n") +
  ";\n";

const marker = "    };\n\n    function detectBrowserLang()";
if (!h.includes(marker)) {
  console.error("marker not found");
  process.exit(1);
}
if (h.includes("I18N.de =")) {
  h = h.replace(/\n    I18N\.de = [\s\S]*?;\n(?=\n    function detectBrowserLang)/, patch);
} else {
  h = h.replace(marker, "    };" + patch + "\n    function detectBrowserLang()");
}
fs.writeFileSync(htmlPath, h, "utf8");
console.log("Injected I18N.de with", Object.keys(de).length, "keys");

function translate(key, en) {
  const map = {
    pageTitle: "VELANTRIM Titan — Konsole",
    "header.subtitle": "V8.7 · Speicher + LLM · API einrichten und chatten",
    "readMode.enter": "Lesen",
    "readMode.exit": "Beenden",
    "readMode.toggleTitle": "Vollbild — nur Chat-Text",
    "readMode.exitTitle": "Lesemodus verlassen (Esc)",
    "readMode.autoScrollHint": "▶ Scrollen… Klick — Stopp",
    "layout.chatOnlyTitle": "Nur Chat — Seitenleisten ausblenden",
    "layout.foldSettings": "Einstellungen einklappen",
    "layout.expandSettings": "Einstellungen anzeigen",
    "search.open": "🔍 Suche",
    "search.placeholder": "Wortsuche…",
    "search.scopeCurrent": "Aktueller Chat",
    "search.scopeAll": "Alle Chats",
    "search.noResults": "Keine Treffer",
    "search.found": "Gefunden: {n}",
    "search.inChat": "in «{title}»",
    "search.user": "Sie",
    "search.unpinHit": "Klicken, um Hervorhebung zu entfernen",
    "lang.label": "Sprache",
    "theme.label": "Design",
    "tts.toggle": "TTS",
    "tts.toggleTitle": "Bot-Antworten vorlesen (Web Speech API)",
    "tts.autoOn": "Auto-Vorlesen an (Sprache aus Text)",
    "tts.autoOff": "Auto-Vorlesen aus — 🔊 an jeder Antwort",
    "tts.unavailable": "Web Speech API nicht verfügbar",
    "tts.speak": "Vorlesen",
    "tts.stop": "Stopp",
    "tts.unavailBrowser": "Sprachausgabe in diesem Browser nicht verfügbar",
    "tts.modeLabel": "Sprachausgabe-Modus",
    "tts.modeBrowser": "① Ohne API — Browser-Stimme (kostenlos)",
    "tts.modeGemini": "② Google Gemini TTS — AIza…-Schlüssel",
    "tts.modeOpenai": "③ OpenAI TTS — sk-…-Schlüssel (mp3-Stream)",
    "tts.voiceLabel": "Stimme",
    "tts.modelLabel": "TTS-Modell",
    "tts.keyLabel": "API-Schlüssel für Sprache",
    "tts.keyGemini": "Google-Gemini-Schlüssel (AIza…) für TTS",
    "tts.keyOpenai": "OpenAI-Schlüssel (sk-…) für TTS",
    "tts.placeholderKey": "API-Schlüssel einfügen",
    "tts.placeholderGemini": "AIza… von aistudio.google.com/apikey",
    "tts.placeholderOpenai": "sk-… von platform.openai.com",
    "tts.browserOk": "✓ Ohne API — kein Schlüssel nötig, 🔊 bei Bot-Antworten",
    "tts.testKey": "Schlüssel bestätigen",
    "tts.testOk": "✓ Schlüssel bestätigt",
    "tts.playTest": "▶ Stimme testen",
    "tts.playTestOk": "✓ Stimme geprüft",
    "tts.connected": "✓ {provider} verbunden · Stimme «{voice}»",
    "tts.voiceCount": "Verfügbare Stimmen: {n} (Google-Gemini-API-Katalog)",
    "tts.voiceCountOpenai": "OpenAI-Stimmen: {n}",
    "tts.confirmFirstForTest": "Zuerst «Schlüssel bestätigen» klicken.",
    "tts.keyOkPlayTest": "Schlüssel akzeptiert. «Stimme testen» klicken.",
    "tts.hintGemini": "<b>Gemini TTS:</b> 30 Stimmen (Kore, Puck, Charon…). Stimme wählen → AIza…-Schlüssel → <b>Schlüssel bestätigen</b> → <b>Stimme testen</b>.",
    "tts.hintOpenai": "<b>OpenAI TTS:</b> Stimme wählen → sk-…-Schlüssel → bestätigen → Stimme testen. mp3-Stream bei 🔊.",
    "tts.testingVoice": "Testphrase wird abgespielt…",
    "tts.testPhrase": "Velantrim-Sprachtest. Die gewählte Stimme funktioniert.",
    "tts.hintDefault": "Gemini: schneller Start bei erster Phrase. OpenAI: mp3-Stream — Ton kurz nach 🔊.",
    "tts.hintBrowser": "<b>Ohne API:</b> eingebaute Browser-Stimme (Web Speech). 🔊 bei jeder Antwort.",
    "tts.testing": "Prüfe {api}…",
    "tts.keyOk": "Sprach-API-Schlüssel bestätigt.",
    "tts.insertGemini": "Gemini-Schlüssel einfügen (AIza…)",
    "tts.insertOpenai": "OpenAI-Schlüssel einfügen (sk-…)",
    "tts.verifyFirst": "Zuerst Sprach-API-Schlüssel im linken Bereich bestätigen.",
    "tts.noApiNeeded": "Browser-Modus — keine Schlüsselbestätigung nötig.",
    "tts.speakFail": "Sprache: {msg}",
    "tts.toggleTitleApi": "Antworten automatisch vorlesen (gewählter TTS-Modus)",
    "status.ttsDash": "TTS —",
    "status.ttsBrowser": "TTS ✓ Browser",
    "status.ttsGemini": "TTS ✓ Gemini",
    "status.ttsOpenai": "TTS ✓ OpenAI",
    "status.ttsMaybe": "TTS ?",
    "toast.ttsConnected": "TTS {mode} — Schlüssel bestätigt",
    "theme.darkShort": "dunkel",
    "theme.darkTitle": "Dunkel — klassisches dunkles Design",
    "theme.lightShort": "hell",
    "theme.lightTitle": "Hell — minimalistisch",
    "theme.skeuShort": "skeu",
    "theme.skeuTitle": "Skeuomorph — erhabene Buttons",
    "theme.volShort": "3d",
    "theme.volTitle": "Volumetrisches 3D (dunkel)",
    "theme.volLightShort": "3d+",
    "theme.volLightTitle": "Volumetrisches 3D (hell)",
    "theme.bookShort": "buch",
    "theme.bookTitle": "Buch — warmes Papier, Serif",
    "theme.neonShort": "neon",
    "theme.neonTitle": "Neon — dunkel mit Leuchten",
    "section.modeChats": "⚡ Modus und Chats",
    "mode.offlineHint": "Offline: LLM aus; Antworten aus Speicher und Notizen.",
    "mode.onlineHint": "Online: LLM kann im Bereich unten aktiviert werden.",
    "chat.sidebarTitle": "Chats",
    "chat.newChatTitle": "Neuer Chat",
    "chat.emptyList": "Noch keine Chats",
    "chat.pin": "Chat anheften",
    "chat.unpin": "Chat lösen",
    "chat.delete": "Chat löschen",
    "chat.more": "Chat-Menü",
    "chat.pinnedGroup": "Angeheftet",
    "chat.recentGroup": "Chats",
    "section.velantrim": "🔑 1. Velantrim-Schlüssel (Server)",
    "section.llm": "🤖 2. LLM-API (DeepSeek, Gemini, …)",
    "section.voice": "🎤 Spracheingabe (Sprache → Text)",
    "section.profile": "👤 Anfrageprofil",
    "section.fact": "📝 Fakt merken",
    "label.apiUrl": "Basis-URL (für externe Clients)",
    "label.velantrimKey": "VELANTRIM_API_KEY aus .env — nicht DeepSeek/Gemini",
    "placeholder.velantrimKey": "z. B. dev-change-me (aus .env)",
    "hint.apiExternal":
      'Externe Apps: Header <code>X-Api-Key: &lt;Ihr Schlüssel&gt;</code>. Endpunkte: <code>POST /query</code>, <code>POST /chat</code>, <code>GET /health</code>. <a href="/docs" target="_blank" rel="noopener">OpenAPI (/docs)</a>.',
    "hint.velantrim":
      "Zuerst dieses Feld ausfüllen (.env-Schlüssel), dann LLM-Schlüssel unten. Nur im Browser gespeichert (localStorage).",
    "hint.storageOnly": " Nur im Browser gespeichert.",
    "btn.fillVelantrim": "Velantrim-Schlüssel aus .env (localhost)",
    "btn.fillVelantrimServer": "Velantrim-Schlüssel vom Server (localhost)",
    "btn.verifyVelantrim": "Schlüssel prüfen (API + Chat-Test)",
    "btn.verifyVelantrimShort": "Velantrim-Schlüssel prüfen",
    "btn.verifiedVelantrim": "✓ Schlüssel geprüft (API + Chat)",
    "label.llmProvider": "1. Anbieter wählen",
    "label.llmQuick": "Schnellauswahl (Karten)",
    "label.llmCustomModel": "Eigenes Modell (falls nicht in Liste)",
    "placeholder.llmKey": "Schlüssel einfügen",
    "placeholder.customModel": "z. B. deepseek-v4-pro",
    "placeholder.apiKeyGeneric": "API-Schlüssel",
    "banner.provider": "Anbieter: …",
    "banner.subline": "Karte anklicken oder aus Liste wählen",
    "banner.defaultModel": "Standardmodell: {model}",
    "label.llmKeyFor": "2. API-Schlüssel für {name}",
    "label.llmModelFor": "3. Modell ({name})",
    "label.llmModel": "3. Modell",
    "btn.llmOff": "LLM aus",
    "btn.llmOn": "✅ LLM an",
    "btn.confirmKey": "Schlüssel bestätigen",
    "btn.keyConfirmed": "✓ Schlüssel bestätigt",
    "btn.confirmKeyTitle": "Sendet Testanfrage an gewählten Anbieter",
    "hint.llmLoading": "Anbieter werden geladen…",
    "hint.llmBase":
      "💡 Jeder Anbieter braucht eigenen Schlüssel — einfügen, «Schlüssel bestätigen», dann LLM aktivieren.",
    "hint.llmServer": "🖥️ Server hat auch LLM aus .env: <b>{provider}</b>.",
    "hint.llmCurrent": "<br>✅ Aktiv: <b>{name}</b> / {model}",
    "hint.llmFallback": "⚠️ Serverliste nicht verfügbar ({msg}). Eingebaute Anbieter werden genutzt.",
    "hint.llmLoadErr": "LLM-Ladefehler: {msg}",
    "voice.modeLabel": "Erkennungsmodus",
    "voice.modeBrowser": "① Ohne API — Browser (kostenlos, Google in Chrome/Edge)",
    "voice.modeGemini": "② Google Gemini API — AIza…-Schlüssel",
    "voice.modeOpenai": "③ OpenAI API — sk-…-Schlüssel (Whisper)",
    "voice.keyLabel": "Sprach-API-Schlüssel",
    "voice.keyGemini": "Google-Gemini-Schlüssel (AIza…) für Sprache",
    "voice.keyOpenai": "OpenAI-Schlüssel (sk-…) für Sprache (Whisper)",
    "voice.placeholderKey": "API-Schlüssel einfügen",
    "voice.placeholderGemini": "AIza… von aistudio.google.com/apikey",
    "voice.placeholderOpenai": "sk-… von platform.openai.com",
    "voice.browserOk": "✓ Ohne API — kein Schlüssel nötig, 🎤 unten drücken",
    "voice.testKey": "Sprachschlüssel prüfen (API)",
    "voice.testOk": "✓ Sprach-API geprüft",
    "voice.hintPick":
      "Modus wählen. Für kostenlose Eingabe «Ohne API» lassen. 🎤 ist unter dem Chatfeld.",
    "voice.hintBrowser":
      "<b>Ohne API:</b> kostenlos in Chrome/Edge. 🎤 unten → sprechen → 🎤 erneut. <b>Abbrechen</b> setzt zurück.",
    "voice.hintBrowserNo":
      "<b>Ohne API</b> in diesem Browser nicht verfügbar. Gemini oder OpenAI wählen und Schlüssel oben einfügen.",
    "voice.hintGemini":
      "<b>Gemini API:</b> AIza… oben einfügen (oder gleicher Schlüssel wie LLM bei Gemini). Dann 🎤 unten.",
    "voice.hintOpenai": "<b>OpenAI Whisper:</b> sk-… oben einfügen. Dann 🎤 unten.",
    "voice.micBrowser": "Sprache ohne API (Browser)",
    "voice.micGemini": "Sprache über Gemini API",
    "voice.micOpenai": "Sprache über OpenAI Whisper",
    "voice.listening": "Höre zu…",
    "voice.noMic": "Mikrofonzugriff verweigert",
    "voice.notRecognized": "Sprache nicht erkannt",
    "voice.processing": "{api} transkribiert…",
    "voice.doneBrowser": "Fertig (Browser-Stimme)",
    "voice.tryAgain": "Bitte erneut sprechen",
    "voice.doneApi": "Fertig ({api})",
    "voice.fromMic": "Text vom Mikrofon",
    "voice.shortRecording": "Text vom Mikrofon (Aufnahme zu kurz für API)",
    "voice.failRecognize": "Sprache konnte nicht erkannt werden",
    "profile.citizen.title": "Für alle",
    "profile.citizen.tagline": "Einfacher persönlicher Assistent: fragen — Antwort aus dem Speicher",
    "profile.personal.title": "Persönlicher Bot",
    "profile.personal.tagline": "Ziele, Gewohnheiten, Notizen — Speicher nur für Sie",
    "profile.company.title": "Unternehmen",
    "profile.company.tagline": "Unternehmensspeicher: Fakten, Audit, Limits, Systemzustand",
    "profile.science.title": "Wissenschaft",
    "profile.science.tagline": "Fakten, Quellen, Kausalität — für Forschungsarbeit",
    "profile.education.title": "Bildung",
    "profile.education.tagline": "Kurse, Notizen, Prüfungen — Speicher für Lernende oder Lehrende",
    "profile.research.title": "Forschung",
    "profile.research.tagline": "Maximale Verknüpfungen, Cross-Domain, Cognitive Runtime",
    "profile.developer.title": "Entwickler",
    "profile.developer.tagline": "Alle ExoCortex-Schichten — Dev-Profil",
    "profile.loading": "Laden…",
    "profile.server": "Server: <b>{emoji} {title}</b>. Anderes Profil im Chat wählbar.",
    "profile.none": "Kein Serverprofil — Karte oben wählen.",
    "right.tabInstructions": "Anweisungen",
    "right.tabMemory": "Speicher",
    "right.tabEssence": "Essenz",
    "right.instructionsHint": "Zusätzliche LLM-Regeln: Ton, Prioritäten, Antwortformat.",
    "right.instructionsPlaceholder": "Z. B. kurz antworten; Daten und Namen speichern…",
    "right.autoSave": "Wichtige Fakten aus Chat automatisch speichern",
    "right.autoSaveBlock": "Automatisch in Speicherblock aus Chat",
    "right.persistSystem": "Auch im Velantrim-System speichern",
    "right.blockMemory": "🧩 Speicherblock",
    "right.notes": "📝 Notizen",
    "notes.btnAdd": "＋ Hinzufügen",
    "notes.btnRefresh": "Aktualisieren",
    "notes.empty": "Noch keine Notizen.",
    "notes.prompt": "Notiztext:",
    "notes.editPrompt": "Bearbeitungsanweisung:",
    "block.btnAdd": "＋ Hinzufügen",
    "block.btnClear": "Leeren",
    "block.btnEdit": "Bearbeiten",
    "block.btnDelete": "Löschen",
    "block.btnSave": "Speichern",
    "block.btnToSystem": "Ins System",
    "block.empty": "Block leer. Chatten oder «Hinzufügen».",
    "block.savedToast": "🧩 Im Speicherblock: {n}",
    "block.cleared": "Speicherblock geleert",
    "memory.flyoutBlock": "Im Block gespeichert",
    "right.memoryHint":
      "Notizen im Speicherblock (Browser). Neue Chats und LLM sehen sie. Rechts bearbeitbar.",
    "right.memoryHighlights": "Jetzt im Kontext",
    "right.memorySuggestions": "Kann gespeichert werden",
    "right.memoryAll": "Gesamter Speicher",
    "right.memoryContextFold": "Kontext und Systemspeicher",
    "essence.testBadge": "⚗️ Testsystem · Browser",
    "essence.hint": "Lebende Dialog-Essenz: Thema, Knoten, Verknüpfungen — nicht der volle Chat-Text.",
    "essence.live": "Tab beim Senden öffnen",
    "essence.waiting": "Warte auf Nachricht…",
    "essence.nodes": "Knoten",
    "essence.edges": "Verknüpfungen",
    "essence.docLink": "Doku: Browser-Testkonsole",
    "essence.phase.read": "Phase: Nachricht lesen",
    "essence.phase.link": "Phase: mit Speicher verknüpfen",
    "essence.phase.commit": "Phase: festhalten",
    "chat.newChat": "＋ Neuer Chat",
    "chat.copyAll": "📋 Ganzen Chat kopieren",
    "chat.newSession": "🆕 Neuer Chat. Vorheriger Dialog wurde als Kontext an das Modell übergeben.",
    "chat.newSessionEmpty":
      "🆕 Neuer Chat. Nachricht schreiben — wichtige Fakten werden automatisch gespeichert.",
    "chat.previousContext": "📎 Kontext des vorherigen Chats:\n{summary}",
    "chat.defaultTitle": "Aktueller Chat",
    "chat.stream": "Antwort streamen",
    "chat.expand": "Erweitern",
    "chat.fold": "Einklappen",
    "chat.clearInput": "Eingabe leeren",
    "chat.attachBtn": "Langen Text anhängen",
    "chat.attachRemove": "Anhang entfernen",
    "chat.attachChip": "📎 Text · {n} Zeichen",
    "chat.attachChipLines": "📎 Text · {n} Zeilen",
    "chat.typing": "Tippt…",
    "chat.thinking": "🧠 Denkt nach…",
    "hint.llmMaxTokens": "Bis 40.000 für lange Antworten. DeepSeek V4 API unterstützt sehr große Ausgaben.",
    "label.deepseekThinking": "4. Thinking (DeepSeek V4)",
    "deepseek.thinkOff": "Aus — schnelle Antwort",
    "deepseek.thinkHigh": "High — Reasoning",
    "deepseek.thinkMax": "X-High (max) — tiefes Reasoning",
    "label.llmMaxTokens": "Max. Antwort-Tokens",
    "memory.savedToast": "💾 Im Speicher gespeichert: {n}",
    "memory.suggestToast": "💡 Für Speicher gefunden: {n} — unten speichern",
    "memory.noneToast": "Auto-Speichern: keine Schlüsselfakten in Nachricht",
    "memory.btnSave": "Speichern",
    "memory.btnSaveAll": "Alle speichern",
    "right.memoryEmpty": "Speicher leer. Chatten oder Fakt links speichern.",
    "memory.flyoutSaved": "Im Speicher gespeichert",
    "memory.flyoutDedup": "Bereits im Speicher",
    "memory.flyoutWhere": "Speicher: {store} · {category}",
    "fact.placeholder": "Faktentext…",
    "btn.saveFact": "Im Speicher speichern",
    "chat.placeholder": "Tippen oder 🎤… Enter zum Senden",
    "btn.send": "Senden",
    "btn.cancel": "Abbrechen",
    "btn.copy": "Kopieren",
    "btn.edit": "Bearbeiten",
    "btn.save": "Speichern",
    "btn.resend": "Erneut senden",
    "btn.clear": "Leeren",
    "btn.showKey": "Schlüssel anzeigen",
    "btn.hideKey": "Schlüssel verbergen",
    "copy.url": "URL kopieren",
    "copy.key": "Schlüssel kopieren",
    "copy.llmKey": "LLM-Schlüssel kopieren",
    "toast.nothing": "Nichts zu kopieren",
    "toast.copied": "Kopiert",
    "toast.copyFail": "Kopieren fehlgeschlagen",
    "toast.msgCopied": "Text kopiert",
    "toast.chatCopied": "Ganzer Chat kopiert",
    "toast.velantrimFilled": "Velantrim-Schlüssel eingesetzt",
    "toast.voiceConnected": "Sprache {mode} — API verbunden",
    "status.velUnknown": "Velantrim ?",
    "status.velOk": "Velantrim ✓ API+Chat",
    "status.velBad": "Velantrim ungeprüft",
    "status.llmOn": "{name} an",
    "status.llmOff": "LLM aus",
    "status.llmOk": "LLM ✓",
    "status.llmMaybe": "LLM ?",
    "status.llmDash": "LLM —",
    "status.voiceDash": "Sprache —",
    "status.voiceBrowser": "Sprache ✓ Browser",
    "status.voiceGemini": "Sprache ✓ Gemini",
    "status.voiceOpenai": "Sprache ✓ OpenAI",
    "status.voiceMaybe": "Sprache ?",
    "llm.keyVerifiedTag": " · Schlüssel ✓ geprüft",
    "llm.keyUnverifiedTag": " · Schlüssel (ungeprüft)",
    "llm.modelSaved": " (gespeichert)",
    "llm.alreadyVerified": "Schlüssel {name} für aktuellen Wert bereits geprüft.",
    "llm.geminiDiscovered": "Gemini-Liste von API: {count} Modelle",
    "meta.profile": "Profil: {name}",
    "meta.memory": "📚 Speicher",
    "meta.facts": "{n} Fakten · {ms} ms",
    "meta.empty": "(leer)",
    "meta.emptyAnswer": "(leere Antwort)",
    "auth.checking": "Abgleich mit Server…",
    "auth.probing": "API-Anfrage (Speicher + Chat)…",
    "auth.badResponse": "Ungültige Serverantwort.",
    "auth.httpFail": "Server lehnte Prüfung ab (HTTP {code}).",
    "auth.noServer": "Server nicht erreichbar. scripts\\start_console.ps1 ausführen",
    "auth.fail": "Velantrim-Schlüssel bestand API-Prüfung nicht.",
    "auth.ok": "Schlüssel geprüft — Chat verfügbar.",
    "auth.filledOk": "Schlüssel eingesetzt und geprüft.",
    "auth.filledFail": "Schlüssel vom Server konnte nicht geprüft werden.",
    "auth.insertKey": "VELANTRIM_API_KEY aus .env ins obere Feld einfügen.",
    "auth.notVerified": "Schlüssel bestand API-Prüfung nicht.",
    "auth.beforeSend": "Schlüssel vor Senden prüfen…",
    "auth.notVerifiedShort": "Schlüsselprüfung fehlgeschlagen.",
    "auth.llmInTop": "Oberes Feld hatte LLM-Schlüssel — in «LLM-API»-Block verschieben.",
    "auth.missingKey":
      "⚠️ Velantrim-Schlüssel in «1. Velantrim-Schlüssel (Server)» nötig — VELANTRIM_API_KEY aus .env.\n\nDeepSeek / Gemini / OpenAI-Schlüssel gehören in «2. LLM-API» — anderer Schlüssel.",
    "auth.missingKeyLocal":
      "\n\n«Velantrim-Schlüssel vom Server» oder «Velantrim-Schlüssel prüfen» (mit start_console.ps1 oft dev-console-key, nicht dev-change-me).",
    "auth.help401":
      "Ungültiger Velantrim-Schlüssel (X-Api-Key).\n\nOberes Feld = VELANTRIM_API_KEY aus .env (nicht DeepSeek/Gemini).\n«Velantrim-Schlüssel prüfen» oder «Schlüssel aus .env».",
    "err.llmKeyMissing": "⚠️ LLM-API-Schlüssel einfügen (Feld unter Anbieter).",
    "err.llmConfirmFirst": "Zuerst «Schlüssel bestätigen» — LLM ohne erfolgreichen Test nicht aktiv.",
    "err.llmNotVerified": "⚠️ Schlüssel ungeprüft. «Schlüssel bestätigen» und auf ✓ warten.",
    "err.llmKeyInChat": "LLM-API-Schlüssel einfügen (nicht Velantrim-Schlüssel).",
    "err.llmOnNoKey": "⚠️ LLM an: LLM-Schlüssel ins zweite Feld (OpenAI / DeepSeek / …).",
    "err.llmNotConfirmed": "⚠️ LLM-Schlüssel nicht bestätigt — «Schlüssel bestätigen».",
    "err.llmInTopField":
      "⚠️ Oberes Feld sieht wie LLM-Schlüssel aus (sk-… / AIza…).\n\nIn «2. LLM-API» verschieben, oben VELANTRIM_API_KEY aus .env.",
    "err.verifyVelantrimBtn": "\n\n«Velantrim-Schlüssel prüfen» — API- und Chat-Test müssen bestehen.",
    "err.sendMeta": "Prüfen: 1) Velantrim-Schlüssel 2) LLM-Schlüssel 3) Anbieter 4) Server neu starten",
    "err.sendPrefix": "Fehler: {msg}",
    "err.keyMeta": "Server-Schlüssel ≠ LLM-Schlüssel",
    "err.llmTestPending": "Prüfe {provider} / {model}…",
    "err.llmTestOk": "✅ Schlüssel geprüft: {provider} / {model}. Antwort: {preview}",
    "err.llmTestBotOk": "✅ LLM-Schlüssel bestätigt: {provider} / {model}\n{preview}",
    "err.llmTestFail": "❌ LLM-Test: {msg}",
    "fact.saved": "Gemerkt: {text}",
    "fact.fail": "Nicht gespeichert: {msg}",
    "voice.noApiNeeded": "Modus ohne API — Schlüsselprüfung nicht nötig.",
    "voice.insertOpenai": "OpenAI sk-…-Schlüssel oben einfügen.",
    "voice.insertGemini": "Gemini AIza…-Schlüssel oben einfügen.",
    "voice.testingStt": "STT {api} wird geprüft…",
    "voice.keyOk": "Schlüssel geprüft.",
    "voice.response": " Antwort: «{text}»",
    "voice.needOpenaiKey": "OpenAI sk-…-Schlüssel links in «Spracheingabe» setzen.",
    "voice.needGeminiKey": "Gemini AIza…-Schlüssel links in «Spracheingabe» setzen.",
    "boot.noLlm": "⚠️ Server ohne LLM-API. Alten uvicorn stoppen und ausführen:\nscripts\\start_console.ps1",
    "boot.noChat": "⚠️ Kein /chat — scripts\\start_console.ps1 neu starten",
    "welcome.bot":
      "Hallo! 🔱\n\nZwei Schlüssel:\n1) Oben — VELANTRIM_API_KEY aus .env (Server-Schlüssel)\n2) Unten — LLM-Schlüssel (DeepSeek, Gemini, OpenAI…)\n\nDann: Anbieter → «Schlüssel bestätigen» → «LLM an» → Chat\n\n🎤 Sprachblock links: ohne API (kostenlos) oder Gemini/OpenAI. 🎤 unten am Chat.",
    "boot.serverDown": "Server nicht verfügbar: {msg}\nAusführen: scripts\\start_console.ps1",
    "label.llmKeyGeneric": "2. API-Schlüssel für gewählten Anbieter",
    "label.llmProviderAria": "LLM-Anbieter",
    "label.voiceModeAria": "Spracheingabe-Modus",
    "voice.micTitle": "Spracheingabe",
    "voice.cancelTitle": "Aufnahme abbrechen",
    "link.profiles": "Profile",
    "auth.verifiedShort": "Schlüssel geprüft.",
    "auth.llmInTopField":
      "Oberes Feld hatte LLM-Schlüssel. In «LLM-API» verschieben; oben VELANTRIM_API_KEY aus .env.",
    "auth.missingKeySuffix":
      "DeepSeek / Gemini / OpenAI-Schlüssel unten in «2. LLM-API» — anderer Schlüssel.",
    "err.llmTestOkShort": "✅ Schlüssel geprüft: {provider} / {model}. Antwort: {preview}",
    "err.llmTestFailPrefix": "❌ LLM-Test: {msg}",
    "err.llmOnNoKeyShort": "⚠️ LLM an: LLM-Schlüssel ins zweite Feld (OpenAI / DeepSeek / …).",
    "err.llmNotConfirmedShort": "⚠️ LLM-Schlüssel nicht bestätigt — «Schlüssel bestätigen».",
    "err.verifyVelantrimSend":
      "⚠️ {hint}\n\n«Velantrim-Schlüssel prüfen» — API- und Chat-Test müssen bestehen.",
    "voice.listeningBrowser": "Höre zu… (Browser, kostenlos)",
    "voice.listeningApi": "Höre zu… ({api})",
    "voice.listeningApiLive": "Höre zu… Browser-Livetext, final prüft {api}",
    "voice.livePreviewUnavailable": "Livetext nicht verfügbar; finale Transkription nach Stopp",
    "voice.stopBrowser": "Aufnahme stoppen (Browser)",
    "voice.stopApi": "Stoppen und an API senden",
    "voice.browserUnavailable":
      "⚠️ Kostenlose Browser-Stimme in Chrome oder Edge. Oder «Gemini API» und AIza…-Schlüssel.",
    "voice.needOpenaiBlock": "⚠️ OpenAI-Modus: sk-…-Schlüssel links in «🎤 Spracheingabe».",
    "voice.needGeminiBlock": "⚠️ Gemini-Modus: AIza…-Schlüssel links in «🎤 Spracheingabe».",
    "voice.verifyKeyFirst": "Zuerst «Sprachschlüssel prüfen (API)»",
    "voice.verifyKeyFirstBot": "⚠️ Zuerst Sprachschlüssel links mit «Sprachschlüssel prüfen (API)».",
    "voice.micUnavailable": "⚠️ Mikrofon nicht verfügbar. Chrome/Edge oder «Browser»-Modus.",
    "voice.micDeniedUi": "Mikrofonzugriff verweigert",
    "voice.micDeniedBot": "⚠️ Mikrofonzugriff im Browser erlauben.",
    "voice.recordingFail": "⚠️ Aufnahme konnte nicht starten: {msg}",
    "voice.geminiErrLeft": "Gemini: {msg} (Browsertext beibehalten)",
    "voice.geminiErrBot": "⚠️ Sprache (Gemini): {msg}",
  };
  if (map[key]) return map[key];
  return en;
}
